name: CI/CD para MLOps Salud

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Ejecutar pruebas
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests/

      - name: Comentar inicio en PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "CI/CD en acción. Ejecutando tareas …"
            })

      - name: Comentar éxito en PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "CI/CD terminado con éxito."
            })
